# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"shift_bit_eps": "01_sigmoid.ipynb",
         "create_base_vectors": "01_sigmoid.ipynb",
         "create_linear_system": "01_sigmoid.ipynb",
         "BitComparison": "01_sigmoid.ipynb",
         "chebyshev_approximation": "polynomials.ipynb",
         "polynomial_approximation_coefficients": "polynomials.ipynb",
         "plot_graph_function_approximation": "polynomials.ipynb",
         "compute_leaves": "00_tree.ipynb",
         "create_linear_node_comparator": "00_tree.ipynb",
         "create_parent_of": "00_tree.ipynb",
         "create_leaf_to_path": "00_tree.ipynb",
         "tanh_path_to_weight": "00_tree.ipynb",
         "tanh_path_to_linear": "00_tree.ipynb",
         "tanh_linear_leaf_matcher": "00_tree.ipynb",
         "sigmoid_path_to_weight": "01_sigmoid.ipynb",
         "sigmoid_path_to_linear": "00_tree.ipynb",
         "sigmoid_linear_leaf_matcher": "00_tree.ipynb",
         "sigmoid_classification_head": "00_tree.ipynb",
         "DecisionTree": "00_tree.ipynb",
         "DEFAULT_POLYNOMIAL_DEGREE": "00_tree.ipynb",
         "DEFAULT_DILATATION_FACTOR": "00_tree.ipynb",
         "DEFAULT_BOUND": "00_tree.ipynb",
         "raise_error_wrong_tree": "00_tree.ipynb",
         "SigmoidDecisionTree": "00_tree.ipynb",
         "SigmoidClassificationTree": "00_tree.ipynb",
         "tanh_classification_head": "00_tree.ipynb",
         "TanhDecisionTree": "00_tree.ipynb",
         "TanhClassificationTree": "00_tree.ipynb",
         "check_output_range": "00_tree.ipynb",
         "register_output_check": "00_tree.ipynb",
         "print_vector": "seal_helper.ipynb",
         "ptx_value": "seal_helper.ipynb",
         "ctx_value": "seal_helper.ipynb",
         "print_ctx": "seal_helper.ipynb",
         "print_ptx": "seal_helper.ipynb",
         "print_range_ctx": "seal_helper.ipynb",
         "print_range_ptx": "seal_helper.ipynb",
         "create_seal_globals": "seal_helper.ipynb",
         "append_globals_to_builtins": "seal_helper.ipynb",
         "coeffs_to_plaintext": "polynomials.ipynb",
         "compute_all_powers": "polynomials.ipynb",
         "multiply_and_add_coeffs": "polynomials.ipynb",
         "polyeval_tree": "polynomials.ipynb",
         "HomomorphicTreeEvaluator": "04_cryptotree.ipynb",
         "extract_diagonals": "04_cryptotree.ipynb",
         "matrix_multiply_diagonals": "04_cryptotree.ipynb",
         "add_bias_ptx": "04_cryptotree.ipynb",
         "LinearCtx": "04_cryptotree.ipynb",
         "pad_along_axis": "04_cryptotree.ipynb",
         "float_to_ctx": "seal_helper.ipynb",
         "vrep": "seal_helper.ipynb"}

modules = ["tree.py",
           "sigmoid.py",
           "seal_helper.py",
           "polynomials.py",
           "cryptotree.py"]

doc_url = "https://dhuynh95.github.io/cryptotree/"

git_url = "https://github.com/dhuynh95/cryptotree/tree/master/"

def custom_doc_links(name): return None
